name: Run tests

on:
  push:
    branches: [jocelyn-backend]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]  # Adjust this as necessary for other versions

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Set up Python and cache pip
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enabling built-in pip caching

    - name: Cache Python environment
      uses: actions/cache@v4
      id: env-cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pythonenv-${{ matrix.python-version }}-${{ hashFiles('rag/requirements-base.txt') }}
    - name: Install pip dependencies
      if: steps.env-cache.outputs.cache-hit != 'true'
      run: |
        pip install -r rag/requirements-base.txt

    - name: Install remaining dependencies
      run: pip install -r rag/requirements-extend.txt

    - name: Install formatting tools
      run: pip install black isort

    - name: Run isort
      run: isort .

    - name: Run Black
      run: black .

    - name: Commit formatting to PR branch
      if: github.event_name == 'pull_request'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Autoformat code (Black + isort)"
        file_pattern: "*.py"

    - name: Download minerU script
      run: wget https://github.com/opendatalab/MinerU/raw/master/scripts/download_models_hf.py -O download_models_hf.py

    - name: Run minerU script
      run: python download_models_hf.py


    - name: Cache pytest artifacts

      uses: actions/cache@v4
      with:
        path: .pytest_cache
        key: ${{ runner.os }}-pytest-${{ github.sha }}

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run pytest
      run: pytest tests --capture=no  # Disable capturing to allow live logging
